### ISSUE TITLE
Having a issue on Android with a custom renderer

### ISSUE THREAD

**Issue by jaspervanmegroot** [xabre/xamarin-forms-tab-badge#41]
Having a crash on start up with android. iOS is working fine. 
The android example is also working fine. What do I wrong?

Code:
**CustomRenderer:**
`[assembly: ExportRenderer(typeof(MainPage), typeof(MyTabbedPageRenderer))]
namespace Appviseurs.Droid
{
    public class MyTabbedPageRenderer : BadgedTabbedPageRenderer
    {
        private MainPage page;
        private Activity activity;
        .....`

**Mainpage:**
`<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"        
             xmlns:plugin="clr-namespace:Plugin.Badge.Abstractions;assembly=Plugin.Badge.Abstractions"
             x:Class="Appviseurs.Views.TabbedPage.MainPage">
</TabbedPage>`

```
`private void SetMainPage()
        {
            InitializeComponent();
            CreateNavigationPage(new DashboardPage(), "Dashboard", "ic_dashboard.png");
            CreateNavigationPage(new ContactPage(), "Gesprekken", "ic_chat.png");
            CreateNavigationPage(new InfoPage(), "Informatie", "ic_info.png");
            CreateNavigationPage(new SettingsPage(), "Instellingen", "ic_settings.png");
            BackgroundColor = Color.FromHex(DatabaseHandler.GetInstance().kantoor.PrimaryColor);

            BarBackgroundColor = (Color)App.Current.Resources["backgroundNavigationBar"];
            BarTextColor = Color.White;

        }
```

        private void CreateNavigationPage(object objectType, string title, string icon)
        {
            var navigationPage = new NavigationPage((Page)objectType);
            navigationPage.Icon = icon;
            navigationPage.Title = title;

            if(title.Equals("Gesprekken"))
            {
                TabBadge.SetBadgeText(navigationPage, );
                TabBadge.SetBadgeColor(navigationPage, Color.Red);
            }

            NavigationPage.SetHasNavigationBar(navigationPage, false);
            Children.Add(navigationPage);
        }`

**Error:**
`FATAL EXCEPTION: main
                                                                                Process: ...., PID: 16282
                                                                                android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
                                                                                  at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00022] in <aa25dff89f734b22b9ab88fd01c78705>:0 
                                                                                  at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00018] in <aa25dff89f734b22b9ab88fd01c78705>:0 
                                                                                  at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00008] in <97e6692f30fe45028b1e0b834fcf308c>:0 
                                                                                    at (wrapper dynamic-method) System.Object:000c410e-449f-4fa0-9d6d-2295bb8bd28f (intptr,intptr,bool,int,int,int,int)
                                                                                    at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
                                                                                    at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:55)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                    at com.android.internal.policy.DecorView.onLayout(DecorView.java:887)
                                                                                    at android.view.View.layout(View.java:18798)
                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5951)
                                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2648)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2364)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                                    at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by xabre** [comment]
Hi @jaspervanmegroot,

You should try to set the badge properties after adding the NavigationPage to the TabbedPage children. 

The badge renderer expects the layout to already be created before adding the badges.

:)

**Comment by xabre** [comment]
@jaspervanmegroot Is this still an issue?

**Comment by jaspervanmegroot** [comment]
That was indeed the solution! Thanks
